### ISSUE TITLE
USB devices

### ISSUE THREAD

**Issue by pmjohann** [moonbuggy/orange-pi-zero-alpine#1]
Hi,

First let me thank you for your work and making alpine run on the Orange PI Zero!

My question concerns the use of USB devices other than mass storage.
I tried attaching Ethernet adapters, webcams etc. and my finding is that although they are detected and show up in dmesg, the system doesn't acknowledge them (no new avail. network interface, no /dev/video0 etc.) For video I also tried to install related packages with apk like v4l-utils, but still no luck.

I saw in commit d878cc4266d94cfc56efb09896289499bda6f9d8 you added overlay support with some usbhost specific additions, and I thought these were resolved but it's still the same unfortunately.

Could you point me in the right direction how to fix the issue please?

Thank you!

**Comment by moonbuggy** [comment]
Sorry for the slow reply. I've been quite distracted lately.

The existing pre-built images are quite minimal on purpose. My intention so far has been to start with the bare minimum required to support the onboard hardware of the Orange Pi Zero so that I (and others) could add only the kernel modules required for a specific application. I have a vague dream to try and fit everything I need for a certain application onto the SPI flash, which is obviously quite limited.

You can build your own kernel image from this GitHub repo by cloning it and running `make` with appropriate arguments. I expect building with the Orange Pi Zero defconfig from the linux-sunxi repo should enable many common USB devices.

This should be achievable by running:

1. ```./configure``` (optional, but it will alert you to missing dependencies in the build environment)
2. ```make linux-defconfig```
3. ```make install```

If I'm honest, there's a chance that this won't work because the Makefile has undergone significant changes since I last built with the defconfig. If that's the case, that should be a relatively easy fix. I'm unable to test it at the moment because, frankly, my chair is broken and sitting at the computer for any significant period of time hurts my back. :) If you run in to any trouble though, let me know and I should be able to resolve it in the next week or two, once I can use the computer comfortably and have caught up on a few other nerdy fun projects I've been neglecting.

**Comment by moonbuggy** [comment]
BTW, if you don't want to build it yourself, I can (and probably should) put the defconfig build up in this repo ready to go. This will probably take me longer than a week or two though, because I'd want to do some testing of the build before I push it, so it's a bit more involved than any (not necessarily existing) issue with the Makefile. 

So you can wait and see what happens on that front if you prefer, but I can't guarantee any particular time frame on that at the moment. Apologies.

**Comment by moonbuggy** [comment]
I have confirmed the commands I gave above will function, however I had forgotten that the defconfig won't actually support running Alpine in the way the rest of the build process is designed to achieve. I remembered mid-build that this is why I previously hadn't put a pre-built non-minimal/defconfig image in the repo.

Unfortuntely, I have neither the time nor inclination to create a generic build that will work with any common USB devices people might use - my goals lay in the other direction, of creating images that have the bare minimum required for a particular application. This repo is really intended to be a base to build from (for myself and anyone else who is so inclined), not a fully capable distro ready for any use case people might throw at it.

If you don't want to build your own kernel from this repo, your best bet would be to look at the references I have linked in the [README](https://github.com/moonbuggy/orange-pi-zero-alpine) and see if they better suit your needs. I believe [Brichacek's build](https://blog.brichacek.net/linux-kernel-4-15-rc2-for-orangepi-zero-and-orangepi-zero-plus-h5/) will support common USB devices, for example.

Sorry I couldn't be more help, but I'm just not in a position to create and maintain a complete Alpine distro for the Orange Pi Zero that I won't actually be using myself.
